import type { SectionData } from "@/types"

export const sectionsData: Record<string, SectionData> = {
  mente: {
    id: "mente",
    title: "Cultiva tu",
    highlightText: "mente",
    subtitle:
      "Más de 8,000 personas han mejorado su bienestar mental con nuestras herramientas. Descubre técnicas para desarrollar claridad, resiliencia y un estado emocional equilibrado.",
    text: "Cultiva claridad y resiliencia. Descubre herramientas para tu bienestar emocional y cognitivo.",
    cards: [
      {
        id: "diario-guiado",
        title: "Diario Guiado",
        description: "Reflexiona sobre tu día y emociones.",
        slug: "diario-guiado",
        isAvailable: true,
        category: "mente",
      },
      {
        id: "meditacion-mindfulness",
        title: "Meditación Mindfulness",
        description: "Calma tu mente y reduce el estrés.",
        slug: "meditacion-mindfulness",
        isAvailable: false,
        category: "mente",
      },
      {
        id: "visualizacion-positiva",
        title: "Visualización Positiva",
        description: "Manifiesta tus metas y enfoque.",
        slug: "visualizacion-positiva",
        isAvailable: false,
        category: "mente",
      },
      {
        id: "seguimiento-habitos",
        title: "Seguimiento de Hábitos",
        description: "Construye rutinas mentales positivas.",
        slug: "seguimiento-habitos",
        isAvailable: false,
        category: "mente",
      },
      {
        id: "ejercicios-gratitud",
        title: "Ejercicios de Gratitud",
        description: "Fomenta una perspectiva optimista.",
        slug: "ejercicios-gratitud",
        isAvailable: false,
        category: "mente",
      },
      {
        id: "tecnicas-respiracion",
        title: "Técnicas de Respiración",
        description: "Controla la ansiedad al instante.",
        slug: "tecnicas-respiracion",
        isAvailable: false,
        category: "mente",
      },
      {
        id: "mapas-mentales",
        title: "Mapas Mentales",
        description: "Organiza ideas y potencia la creatividad.",
        slug: "mapas-mentales",
        isAvailable: false,
        category: "mente",
      },
      {
        id: "afirmaciones-diarias",
        title: "Afirmaciones Diarias",
        description: "Refuerza tu autoestima y confianza.",
        slug: "afirmaciones-diarias",
        isAvailable: false,
        category: "mente",
      },
    ],
  },
  relaciones: {
    id: "relaciones",
    title: "Fortalece tus",
    highlightText: "relaciones",
    subtitle:
      "Más de 6,000 personas han mejorado sus relaciones con nuestras herramientas. Descubre técnicas para comunicarte mejor, resolver conflictos y construir vínculos más profundos y significativos.",
    text: "Fortalece tus relaciones. Herramientas para mejorar la comunicación, resolver conflictos y construir vínculos significativos.",
    cards: [
      {
        id: "test-lenguajes-amor",
        title: "Test de lenguajes del amor",
        description: "Descubre cómo das y recibes amor.",
        slug: "test-lenguajes-amor",
        isAvailable: true,
        category: "relaciones",
      },
      {
        id: "comunicacion-asertiva",
        title: "Guía de comunicación asertiva",
        description: "Aprende a expresarte con claridad.",
        slug: "comunicacion-asertiva",
        isAvailable: false,
        category: "relaciones",
      },
      {
        id: "resolucion-conflictos",
        title: "Resolución de conflictos",
        description: "Técnicas para resolver desacuerdos.",
        slug: "resolucion-conflictos",
        isAvailable: false,
        category: "relaciones",
      },
      {
        id: "diario-parejas",
        title: "Diario para parejas",
        description: "Fortalece tu conexión diaria.",
        slug: "diario-parejas",
        isAvailable: false,
        category: "relaciones",
      },
      {
        id: "test-apego",
        title: "Test de estilo de apego",
        description: "Entiende tus patrones relacionales.",
        slug: "test-apego",
        isAvailable: false,
        category: "relaciones",
      },
      {
        id: "limites-saludables",
        title: "Establecer límites saludables",
        description: "Aprende a cuidar tu espacio personal.",
        slug: "limites-saludables",
        isAvailable: false,
        category: "relaciones",
      },
      {
        id: "preguntas-profundas",
        title: "Preguntas profundas",
        description: "Generador de conversaciones significativas.",
        slug: "preguntas-profundas",
        isAvailable: false,
        category: "relaciones",
      },
      {
        id: "ejercicios-empatia",
        title: "Ejercicios de empatía",
        description: "Desarrolla tu inteligencia emocional.",
        slug: "ejercicios-empatia",
        isAvailable: false,
        category: "relaciones",
      },
    ],
  },
  cuerpo: {
    id: "cuerpo",
    title: "Energiza tu",
    highlightText: "cuerpo",
    subtitle:
      "Más de 12,000 personas han transformado su salud física con nuestras herramientas. Accede a rutinas, planes nutricionales y consejos para un estilo de vida activo y saludable.",
    text: "Energiza tu cuerpo. Accede a rutinas, nutrición y consejos para un estilo de vida activo y así obtener un bienestar integral.",
    cards: [
      {
        id: "rutinas-hiit",
        title: "Rutinas HIIT",
        description: "Entrenamientos cortos y efectivos.",
        slug: "rutinas-hiit",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "planificador-comidas",
        title: "Planificador de Comidas",
        description: "Organiza tu nutrición semanal.",
        slug: "planificador-comidas",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "yoga-principiantes",
        title: "Yoga para Principiantes",
        description: "Mejora flexibilidad y relajación.",
        slug: "yoga-principiantes",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "monitor-pasos",
        title: "Monitor de Pasos",
        description: "Registra tu actividad diaria.",
        slug: "monitor-pasos",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "recetario-saludable",
        title: "Recetario Saludable",
        description: "Ideas nutritivas y fáciles.",
        slug: "recetario-saludable",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "retos-fitness",
        title: "Retos Fitness",
        description: "Motívate con desafíos semanales.",
        slug: "retos-fitness",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "guia-estiramientos",
        title: "Guía de Estiramientos",
        description: "Previene lesiones y mejora movilidad.",
        slug: "guia-estiramientos",
        isAvailable: false,
        category: "cuerpo",
      },
      {
        id: "calculadora-hidratacion",
        title: "Calculadora Hidratación",
        description: "Asegura tu ingesta de agua.",
        slug: "calculadora-hidratacion",
        isAvailable: true,
        category: "cuerpo",
      },
      {
        id: "calculadora-calorias",
        title: "Calculadora de Calorías",
        description: "Descubre tus calorías diarias.",
        slug: "calculadora-calorias",
        isAvailable: true,
        category: "cuerpo",
      },
    ],
  },
  finanzas: {
    id: "finanzas",
    title: "Domina tus",
    highlightText: "finanzas",
    subtitle:
      "Más de 10,000 personas han mejorado su bienestar financiero con nuestras herramientas. Aprende a presupuestar, invertir y alcanzar tus metas económicas con estrategias probadas.",
    text: "Domina tus finanzas. Herramientas para presupuestar, invertir y alcanzar tus metas económicas.",
    cards: [
      {
        id: "crear-presupuesto-personal",
        title: "Crear presupuesto personal",
        description: "Gestiona ingresos y gastos fácilmente.",
        slug: "crear-presupuesto-personal",
        isAvailable: true,
        category: "finanzas",
      },
      {
        id: "calculadora-interes-compuesto",
        title: "Calculadora interés compuesto",
        description: "Visualiza el crecimiento de ahorros.",
        slug: "calculadora-interes-compuesto",
        isAvailable: true,
        category: "finanzas",
      },
      {
        id: "planificador-ahorros",
        title: "Planificador de ahorros",
        description: "Define objetivos y cómo alcanzarlos.",
        slug: "planificador-ahorros",
        isAvailable: false,
        category: "finanzas",
      },
      {
        id: "calculadora-prestamo",
        title: "Calculadora de préstamo",
        description: "Estrategia para eliminar deudas.",
        slug: "calculadora-prestamo",
        isAvailable: true,
        category: "finanzas",
      },
      {
        id: "calculadora-consumo-electrico",
        title: "Calculadora consumo eléctrico",
        description: "Estima tu factura por kWh y ahorra.",
        slug: "calculadora-consumo-electrico",
        isAvailable: true,
        category: "finanzas",
      },
      {
        id: "tarjeta-corte-vencimiento",
        title: "Corte y vencimiento tarjeta",
        description: "Planea tus compras y pagos.",
        slug: "tarjeta-corte-vencimiento",
        isAvailable: true,
        category: "finanzas",
      },
      {
        id: "test-perfil-riesgo",
        title: "Test de perfíl de riesgo",
        description: "Aprende a ver como inviertes.",
        slug: "test-perfil-riesgo",
        isAvailable: false,
        category: "finanzas",
      },
      {
        id: "comparador-prestamos",
        title: "Comparador Préstamos",
        description: "Analiza opciones de financiación.",
        slug: "comparador-prestamos",
        isAvailable: false,
        category: "finanzas",
      },
      {
        id: "glosario-financiero",
        title: "Glosario Financiero",
        description: "Entiende términos clave.",
        slug: "glosario-financiero",
        isAvailable: false,
        category: "finanzas",
      },
      {
        id: "tracker-gastos-hormiga",
        title: "Tracker Gastos Hormiga",
        description: "Identifica pequeños gastos.",
        slug: "tracker-gastos-hormiga",
        isAvailable: false,
        category: "finanzas",
      },
    ],
  },
}
